# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Имя'),
        ),
    ]
